### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by tpendergrass** [keiwando/evolution#1]
Love this simulation! had to buy it, nice work.

Myself and others are getting an out of memory error in WebGL after X amount of generations.
When running locally on Windows 10, I notice that memory usage starts around 250MB and increases about 6MB per generation when simulating 40 entities for 10 seconds. This increase continues indefinitely.

When I save the simulation, exit it, and load it again, the simulation continues without issue and the memory resets back to around 250MB.

**Comment by keiwando** [comment]
Yes, I'm aware of that problem but I haven't had the time to profile it yet to see what exactly is happening. I'll make sure to fix this in the next big update, but it's unfortunately going to take a couple of months before I can work on this project again.

Thanks a lot for the support and the patience!

**Comment by keiwando** [comment]
Memory leaks should be fixed with today's v3.0.0 release.
