### ISSUE TITLE
Unusual behaviour when bones connected only by muscles

### ISSUE THREAD

**Issue by ishigoya** [keiwando/evolution#17]
It is possible to create creatures where bones are only joined by a muscle, as shown in the image below. 

![20230607_09h00m35s_grim](https://github.com/keiwando/evolution/assets/16798645/6cb927f2-7bc1-4735-9b29-4b3adeb9bf2e)

In simulations, the muscles of such creatures stretch to be very long, behaving in an unexpected way.

![20230607_09h05m59s_grim](https://github.com/keiwando/evolution/assets/16798645/525d9a3c-5b62-457a-bd0a-2f73439b1159)

**Comment by keiwando** [comment]
Here are the relevant FAQ pages regarding this:
https://keiwando.com/evolution/faq/glitch/
https://keiwando.com/evolution/faq/glitch-fix/
