### ISSUE TITLE
Muscle Question

### ISSUE THREAD

**Issue by TheBarret** [keiwando/evolution#9]
Is it possible to manually set the position of a muscle on the bone length?

**Comment by keiwando** [comment]
No, they are always connected to the bone center if that's what you're asking.

**Comment by TheBarret** [comment]
> No, they are always connected to the bone center if that's what you're asking.

What file in the source code is part of that instruction? coz i would love to see where one can be placed on a muscle on the entire length of it.

**Comment by keiwando** [comment]
https://github.com/keiwando/evolution/blob/11d0b2c8ca1792a254ead122f593d291e99e433f/Assets/Scripts/Controllers/CreatureBuilder.cs#L274

This and other lines in that file that set the muscle start and end points based on the `Bone.Center` property.
